# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stt.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stt.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tstt.proto\x12\x06stt.v1\"9\n\x11TranscribeRequest\x12\x0f\n\x07samples\x18\x01 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x05\"\x85\x01\n\x12TranscribeResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\x12\x10\n\x08\x64uration\x18\x03 \x01(\x02\x12\x19\n\x11inference_time_ms\x18\x04 \x01(\x03\x12\x0e\n\x06tokens\x18\x05 \x03(\t\x12\x12\n\ntimestamps\x18\x06 \x03(\x02\"\x15\n\x13GetModelTypeRequest\"*\n\x14GetModelTypeResponse\x12\x12\n\nmodel_type\x18\x01 \x01(\t2\xa1\x01\n\x0fInferenceEngine\x12\x43\n\nTranscribe\x12\x19.stt.v1.TranscribeRequest\x1a\x1a.stt.v1.TranscribeResponse\x12I\n\x0cGetModelType\x12\x1b.stt.v1.GetModelTypeRequest\x1a\x1c.stt.v1.GetModelTypeResponseB@Z>github.com/PhilHem/stt-server/internal/recognizer/remote/sttpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stt_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z>github.com/PhilHem/stt-server/internal/recognizer/remote/sttpb'
  _globals['_TRANSCRIBEREQUEST']._serialized_start=21
  _globals['_TRANSCRIBEREQUEST']._serialized_end=78
  _globals['_TRANSCRIBERESPONSE']._serialized_start=81
  _globals['_TRANSCRIBERESPONSE']._serialized_end=214
  _globals['_GETMODELTYPEREQUEST']._serialized_start=216
  _globals['_GETMODELTYPEREQUEST']._serialized_end=237
  _globals['_GETMODELTYPERESPONSE']._serialized_start=239
  _globals['_GETMODELTYPERESPONSE']._serialized_end=281
  _globals['_INFERENCEENGINE']._serialized_start=284
  _globals['_INFERENCEENGINE']._serialized_end=445
# @@protoc_insertion_point(module_scope)
