# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import stt_pb2 as stt__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in stt_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InferenceEngineStub(object):
    """InferenceEngine is the contract for a remote speech recognition backend.
    stt-server acts as the gRPC client; the backend (PopTorch, libtorch,
    NeMo, etc.) runs as a gRPC server.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Transcribe = channel.unary_unary(
                '/stt.v1.InferenceEngine/Transcribe',
                request_serializer=stt__pb2.TranscribeRequest.SerializeToString,
                response_deserializer=stt__pb2.TranscribeResponse.FromString,
                _registered_method=True)
        self.GetModelType = channel.unary_unary(
                '/stt.v1.InferenceEngine/GetModelType',
                request_serializer=stt__pb2.GetModelTypeRequest.SerializeToString,
                response_deserializer=stt__pb2.GetModelTypeResponse.FromString,
                _registered_method=True)


class InferenceEngineServicer(object):
    """InferenceEngine is the contract for a remote speech recognition backend.
    stt-server acts as the gRPC client; the backend (PopTorch, libtorch,
    NeMo, etc.) runs as a gRPC server.
    """

    def Transcribe(self, request, context):
        """Transcribe runs speech recognition on raw audio samples.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelType(self, request, context):
        """GetModelType returns metadata about the loaded model.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Transcribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Transcribe,
                    request_deserializer=stt__pb2.TranscribeRequest.FromString,
                    response_serializer=stt__pb2.TranscribeResponse.SerializeToString,
            ),
            'GetModelType': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelType,
                    request_deserializer=stt__pb2.GetModelTypeRequest.FromString,
                    response_serializer=stt__pb2.GetModelTypeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stt.v1.InferenceEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('stt.v1.InferenceEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InferenceEngine(object):
    """InferenceEngine is the contract for a remote speech recognition backend.
    stt-server acts as the gRPC client; the backend (PopTorch, libtorch,
    NeMo, etc.) runs as a gRPC server.
    """

    @staticmethod
    def Transcribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stt.v1.InferenceEngine/Transcribe',
            stt__pb2.TranscribeRequest.SerializeToString,
            stt__pb2.TranscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stt.v1.InferenceEngine/GetModelType',
            stt__pb2.GetModelTypeRequest.SerializeToString,
            stt__pb2.GetModelTypeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
