// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: stt.proto

package sttpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TranscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw audio samples as packed IEEE 754 float32, little-endian.
	// Callers must convert from their native format before sending.
	Samples []byte `protobuf:"bytes,1,opt,name=samples,proto3" json:"samples,omitempty"`
	// Sample rate in Hz (e.g. 16000).
	SampleRate    int32 `protobuf:"varint,2,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscribeRequest) Reset() {
	*x = TranscribeRequest{}
	mi := &file_stt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscribeRequest) ProtoMessage() {}

func (x *TranscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscribeRequest.ProtoReflect.Descriptor instead.
func (*TranscribeRequest) Descriptor() ([]byte, []int) {
	return file_stt_proto_rawDescGZIP(), []int{0}
}

func (x *TranscribeRequest) GetSamples() []byte {
	if x != nil {
		return x.Samples
	}
	return nil
}

func (x *TranscribeRequest) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

type TranscribeResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Text            string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Language        string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	Duration        float32                `protobuf:"fixed32,3,opt,name=duration,proto3" json:"duration,omitempty"`                                       // audio duration in seconds
	InferenceTimeMs int64                  `protobuf:"varint,4,opt,name=inference_time_ms,json=inferenceTimeMs,proto3" json:"inference_time_ms,omitempty"` // backend-measured inference time
	Tokens          []string               `protobuf:"bytes,5,rep,name=tokens,proto3" json:"tokens,omitempty"`                                             // per-token text (BPE tokens)
	Timestamps      []float32              `protobuf:"fixed32,6,rep,packed,name=timestamps,proto3" json:"timestamps,omitempty"`                            // per-token start time in seconds
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TranscribeResponse) Reset() {
	*x = TranscribeResponse{}
	mi := &file_stt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscribeResponse) ProtoMessage() {}

func (x *TranscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscribeResponse.ProtoReflect.Descriptor instead.
func (*TranscribeResponse) Descriptor() ([]byte, []int) {
	return file_stt_proto_rawDescGZIP(), []int{1}
}

func (x *TranscribeResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TranscribeResponse) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *TranscribeResponse) GetDuration() float32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *TranscribeResponse) GetInferenceTimeMs() int64 {
	if x != nil {
		return x.InferenceTimeMs
	}
	return 0
}

func (x *TranscribeResponse) GetTokens() []string {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *TranscribeResponse) GetTimestamps() []float32 {
	if x != nil {
		return x.Timestamps
	}
	return nil
}

type GetModelTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelTypeRequest) Reset() {
	*x = GetModelTypeRequest{}
	mi := &file_stt_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelTypeRequest) ProtoMessage() {}

func (x *GetModelTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stt_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelTypeRequest.ProtoReflect.Descriptor instead.
func (*GetModelTypeRequest) Descriptor() ([]byte, []int) {
	return file_stt_proto_rawDescGZIP(), []int{2}
}

type GetModelTypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelType     string                 `protobuf:"bytes,1,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"` // e.g. "nemo_transducer", "whisper"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelTypeResponse) Reset() {
	*x = GetModelTypeResponse{}
	mi := &file_stt_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelTypeResponse) ProtoMessage() {}

func (x *GetModelTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stt_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelTypeResponse.ProtoReflect.Descriptor instead.
func (*GetModelTypeResponse) Descriptor() ([]byte, []int) {
	return file_stt_proto_rawDescGZIP(), []int{3}
}

func (x *GetModelTypeResponse) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

var File_stt_proto protoreflect.FileDescriptor

const file_stt_proto_rawDesc = "" +
	"\n" +
	"\tstt.proto\x12\x06stt.v1\"N\n" +
	"\x11TranscribeRequest\x12\x18\n" +
	"\asamples\x18\x01 \x01(\fR\asamples\x12\x1f\n" +
	"\vsample_rate\x18\x02 \x01(\x05R\n" +
	"sampleRate\"\xc4\x01\n" +
	"\x12TranscribeResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x02R\bduration\x12*\n" +
	"\x11inference_time_ms\x18\x04 \x01(\x03R\x0finferenceTimeMs\x12\x16\n" +
	"\x06tokens\x18\x05 \x03(\tR\x06tokens\x12\x1e\n" +
	"\n" +
	"timestamps\x18\x06 \x03(\x02R\n" +
	"timestamps\"\x15\n" +
	"\x13GetModelTypeRequest\"5\n" +
	"\x14GetModelTypeResponse\x12\x1d\n" +
	"\n" +
	"model_type\x18\x01 \x01(\tR\tmodelType2\xa1\x01\n" +
	"\x0fInferenceEngine\x12C\n" +
	"\n" +
	"Transcribe\x12\x19.stt.v1.TranscribeRequest\x1a\x1a.stt.v1.TranscribeResponse\x12I\n" +
	"\fGetModelType\x12\x1b.stt.v1.GetModelTypeRequest\x1a\x1c.stt.v1.GetModelTypeResponseB@Z>github.com/PhilHem/stt-server/internal/recognizer/remote/sttpbb\x06proto3"

var (
	file_stt_proto_rawDescOnce sync.Once
	file_stt_proto_rawDescData []byte
)

func file_stt_proto_rawDescGZIP() []byte {
	file_stt_proto_rawDescOnce.Do(func() {
		file_stt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stt_proto_rawDesc), len(file_stt_proto_rawDesc)))
	})
	return file_stt_proto_rawDescData
}

var file_stt_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_stt_proto_goTypes = []any{
	(*TranscribeRequest)(nil),    // 0: stt.v1.TranscribeRequest
	(*TranscribeResponse)(nil),   // 1: stt.v1.TranscribeResponse
	(*GetModelTypeRequest)(nil),  // 2: stt.v1.GetModelTypeRequest
	(*GetModelTypeResponse)(nil), // 3: stt.v1.GetModelTypeResponse
}
var file_stt_proto_depIdxs = []int32{
	0, // 0: stt.v1.InferenceEngine.Transcribe:input_type -> stt.v1.TranscribeRequest
	2, // 1: stt.v1.InferenceEngine.GetModelType:input_type -> stt.v1.GetModelTypeRequest
	1, // 2: stt.v1.InferenceEngine.Transcribe:output_type -> stt.v1.TranscribeResponse
	3, // 3: stt.v1.InferenceEngine.GetModelType:output_type -> stt.v1.GetModelTypeResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_stt_proto_init() }
func file_stt_proto_init() {
	if File_stt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stt_proto_rawDesc), len(file_stt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stt_proto_goTypes,
		DependencyIndexes: file_stt_proto_depIdxs,
		MessageInfos:      file_stt_proto_msgTypes,
	}.Build()
	File_stt_proto = out.File
	file_stt_proto_goTypes = nil
	file_stt_proto_depIdxs = nil
}
