// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: stt.proto

package sttpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InferenceEngine_Transcribe_FullMethodName   = "/stt.v1.InferenceEngine/Transcribe"
	InferenceEngine_GetModelType_FullMethodName = "/stt.v1.InferenceEngine/GetModelType"
)

// InferenceEngineClient is the client API for InferenceEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// InferenceEngine is the contract for a remote speech recognition backend.
// stt-server acts as the gRPC client; the backend (PopTorch, libtorch,
// NeMo, etc.) runs as a gRPC server.
type InferenceEngineClient interface {
	// Transcribe runs speech recognition on raw audio samples.
	Transcribe(ctx context.Context, in *TranscribeRequest, opts ...grpc.CallOption) (*TranscribeResponse, error)
	// GetModelType returns metadata about the loaded model.
	GetModelType(ctx context.Context, in *GetModelTypeRequest, opts ...grpc.CallOption) (*GetModelTypeResponse, error)
}

type inferenceEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewInferenceEngineClient(cc grpc.ClientConnInterface) InferenceEngineClient {
	return &inferenceEngineClient{cc}
}

func (c *inferenceEngineClient) Transcribe(ctx context.Context, in *TranscribeRequest, opts ...grpc.CallOption) (*TranscribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TranscribeResponse)
	err := c.cc.Invoke(ctx, InferenceEngine_Transcribe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceEngineClient) GetModelType(ctx context.Context, in *GetModelTypeRequest, opts ...grpc.CallOption) (*GetModelTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetModelTypeResponse)
	err := c.cc.Invoke(ctx, InferenceEngine_GetModelType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InferenceEngineServer is the server API for InferenceEngine service.
// All implementations must embed UnimplementedInferenceEngineServer
// for forward compatibility.
//
// InferenceEngine is the contract for a remote speech recognition backend.
// stt-server acts as the gRPC client; the backend (PopTorch, libtorch,
// NeMo, etc.) runs as a gRPC server.
type InferenceEngineServer interface {
	// Transcribe runs speech recognition on raw audio samples.
	Transcribe(context.Context, *TranscribeRequest) (*TranscribeResponse, error)
	// GetModelType returns metadata about the loaded model.
	GetModelType(context.Context, *GetModelTypeRequest) (*GetModelTypeResponse, error)
	mustEmbedUnimplementedInferenceEngineServer()
}

// UnimplementedInferenceEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInferenceEngineServer struct{}

func (UnimplementedInferenceEngineServer) Transcribe(context.Context, *TranscribeRequest) (*TranscribeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Transcribe not implemented")
}
func (UnimplementedInferenceEngineServer) GetModelType(context.Context, *GetModelTypeRequest) (*GetModelTypeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetModelType not implemented")
}
func (UnimplementedInferenceEngineServer) mustEmbedUnimplementedInferenceEngineServer() {}
func (UnimplementedInferenceEngineServer) testEmbeddedByValue()                         {}

// UnsafeInferenceEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InferenceEngineServer will
// result in compilation errors.
type UnsafeInferenceEngineServer interface {
	mustEmbedUnimplementedInferenceEngineServer()
}

func RegisterInferenceEngineServer(s grpc.ServiceRegistrar, srv InferenceEngineServer) {
	// If the following call panics, it indicates UnimplementedInferenceEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InferenceEngine_ServiceDesc, srv)
}

func _InferenceEngine_Transcribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TranscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceEngineServer).Transcribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceEngine_Transcribe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceEngineServer).Transcribe(ctx, req.(*TranscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceEngine_GetModelType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceEngineServer).GetModelType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceEngine_GetModelType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceEngineServer).GetModelType(ctx, req.(*GetModelTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InferenceEngine_ServiceDesc is the grpc.ServiceDesc for InferenceEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InferenceEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stt.v1.InferenceEngine",
	HandlerType: (*InferenceEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Transcribe",
			Handler:    _InferenceEngine_Transcribe_Handler,
		},
		{
			MethodName: "GetModelType",
			Handler:    _InferenceEngine_GetModelType_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stt.proto",
}
